### ISSUE TITLE
Running `mux init` twice doesn't update the credentials

### ISSUE THREAD

**Issue by heff** [muxinc/cli#4] opened 2020-03-12 21:25 UTC
I'm working with two different orgs and needing to switch the token credentials. I ran `mux init` again and everything appeared to work, but then when I uploaded a new asset, it uploaded it to the previous account, not the one I just initialized.

**Comment by mmcc** [comment] 2020-08-13 21:36
Just tried to reproduce this and can't seem to. Can someone else see if this is still the case?

**Comment by mmcc** [comment] 2020-08-13 23:19
Closing this because I can't repro, but feel free to open it if you run into it again!

**Closed by mmcc** 2020-08-13 23:19 UTC
